choco install vscode.install -y
choco install Wget -y
choco install WhatsApp -y
choco install winrar -y
choco install neovim -y
choco install powershell-core -y
choco install office365proplus -y
choco install vmwareworkstation -y
choco install git.install -y
choco install GoogleChrome -y
choco install foxitreader -y
choco install freecommander-xe.install -y
choco install Firefox -y
choco install dropbox -y